// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: anki_vector/messaging/extensions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Anki.Vector.ExternalInterface {

  /// <summary>Holder for reflection information generated from anki_vector/messaging/extensions.proto</summary>
  public static partial class ExtensionsReflection {

    #region Descriptor
    /// <summary>File descriptor for anki_vector/messaging/extensions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExtensionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZhbmtpX3ZlY3Rvci9tZXNzYWdpbmcvZXh0ZW5zaW9ucy5wcm90bxIeQW5r",
            "aS5WZWN0b3IuZXh0ZXJuYWxfaW50ZXJmYWNlGiBnb29nbGUvcHJvdG9idWYv",
            "ZGVzY3JpcHRvci5wcm90bzozCghzdHJlYW1lZBIfLmdvb2dsZS5wcm90b2J1",
            "Zi5NZXNzYWdlT3B0aW9ucxjg1AMgASgIYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
