// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: anki_vector/messaging/response_status.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Anki.Vector.ExternalInterface {

  /// <summary>Holder for reflection information generated from anki_vector/messaging/response_status.proto</summary>
  public static partial class ResponseStatusReflection {

    #region Descriptor
    /// <summary>File descriptor for anki_vector/messaging/response_status.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResponseStatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CithbmtpX3ZlY3Rvci9tZXNzYWdpbmcvcmVzcG9uc2Vfc3RhdHVzLnByb3Rv",
            "Eh5BbmtpLlZlY3Rvci5leHRlcm5hbF9pbnRlcmZhY2Ui6AEKDlJlc3BvbnNl",
            "U3RhdHVzEkcKBGNvZGUYASABKA4yOS5BbmtpLlZlY3Rvci5leHRlcm5hbF9p",
            "bnRlcmZhY2UuUmVzcG9uc2VTdGF0dXMuU3RhdHVzQ29kZSKMAQoKU3RhdHVz",
            "Q29kZRILCgdVTktOT1dOEAASFQoRUkVTUE9OU0VfUkVDRUlWRUQQARIWChJS",
            "RVFVRVNUX1BST0NFU1NJTkcQAhIGCgJPSxADEg0KCUZPUkJJRERFThBkEg0K",
            "CU5PVF9GT1VORBBlEhwKGEVSUk9SX1VQREFURV9JTl9QUk9HUkVTUxBmYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Anki.Vector.ExternalInterface.ResponseStatus), global::Anki.Vector.ExternalInterface.ResponseStatus.Parser, new[]{ "Code" }, null, new[]{ typeof(global::Anki.Vector.ExternalInterface.ResponseStatus.Types.StatusCode) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// A shared response message sent back as part of most requests.
  /// This will indicate the generic state of the request.
  /// </summary>
  public sealed partial class ResponseStatus : pb::IMessage<ResponseStatus> {
    private static readonly pb::MessageParser<ResponseStatus> _parser = new pb::MessageParser<ResponseStatus>(() => new ResponseStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResponseStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Anki.Vector.ExternalInterface.ResponseStatusReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseStatus(ResponseStatus other) : this() {
      code_ = other.code_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseStatus Clone() {
      return new ResponseStatus(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private global::Anki.Vector.ExternalInterface.ResponseStatus.Types.StatusCode code_ = 0;
    /// <summary>
    /// The generic status code to give high-level insight into the progress of a given message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Anki.Vector.ExternalInterface.ResponseStatus.Types.StatusCode Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResponseStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResponseStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != 0) hash ^= Code.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResponseStatus other) {
      if (other == null) {
        return;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            code_ = (global::Anki.Vector.ExternalInterface.ResponseStatus.Types.StatusCode) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ResponseStatus message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum StatusCode {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        /// <summary>
        /// The message has completed as expected.
        /// </summary>
        [pbr::OriginalName("RESPONSE_RECEIVED")] ResponseReceived = 1,
        /// <summary>
        /// The message has been sent to the robot.
        /// </summary>
        [pbr::OriginalName("REQUEST_PROCESSING")] RequestProcessing = 2,
        /// <summary>
        /// The message has been handled successfully at the interface level.
        /// </summary>
        [pbr::OriginalName("OK")] Ok = 3,
        /// <summary>
        /// The user was not authorizied.
        /// </summary>
        [pbr::OriginalName("FORBIDDEN")] Forbidden = 100,
        /// <summary>
        /// The requested attribute was not found.
        /// </summary>
        [pbr::OriginalName("NOT_FOUND")] NotFound = 101,
        /// <summary>
        /// Currently updating values from another call.
        /// </summary>
        [pbr::OriginalName("ERROR_UPDATE_IN_PROGRESS")] ErrorUpdateInProgress = 102,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
